### ISSUE TITLE
Incorrect handling of spaces between encoded words

### ISSUE THREAD

**Issue by jathd** [eugeneia/cl-rfc2047#1]
RFC 2047 specifies (p. 11):

> Any amount of linear-space-white between 'encoded-word's,
>            even if it includes a CRLF followed by one or more SPACEs,
>            is ignored for the purposes of display.

The spaces are currently preserved:

``` lisp
> (cl-rfc2047:decode* "=?ISO-8859-1?Q?a?= =?ISO-8859-1?Q?b?=")
"a b"
```

(The expected result is `"ab"`.)

A more complete test case might be

``` lisp
(cl-rfc2047:decode* 
 (format nil "=?ISO-8859-1?Q?a?=  ~A  ~:*~A  =?ISO-8859-1?Q?b?=" 
         cl-rfc2047::*crlfsp*))
```

with expected result `"ab"`.

**Comment by eugeneia** [comment]
Thank you for reporting this issue. Will take a look as soon as possible.

**Comment by eugeneia** [comment]
@jathd I just pushed a fix and the proposed test case. Please close this issue if you are satisfied.
